on:
    push:
        branches:
            - main
  
permissions:
    contents: write
    issues: write
    pull-requests: write
  
name: release-please
  
jobs:
    release-please:
        if: github.repository == 'obbywiki/mediawiki-extensions-UserFlairs'
        runs-on: ubuntu-latest

        steps:
        - uses: googleapis/release-please-action@v4
          with:
            token: ${{ secrets.MASTER_RELEASE_TOKEN }}