-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uf_group_flair (
  ufgf_group VARBINARY(255) NOT NULL,
  ufgf_file VARBINARY(255) NOT NULL,
  ufgf_priority INT NOT NULL DEFAULT 0,
  ufgf_updated_at BINARY(14) NOT NULL,
  PRIMARY KEY(ufgf_group)
) /*$wgDBTableOptions*/;
